version: '3.3'
services:
  web:
    build: .
    command: npm run dev
    depends_on:
      - db
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    env_file: ./.env

  db:
    image: mysql:5.7.32
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cst336-final
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  migration:
    build: .
    command: >
      bash -c "./wait-for-it/wait-for-it.sh -t 30 db:3306 -- npm run migrate"
    depends_on:
      - db
    env_file: ./.env
    volumes:
      - ./migrations:/usr/app/migrations


# Names our volume
volumes:
  my-db: